#!/usr/bin/env python

import requests

r = requests.get('https://www.bus-conf.org/')

print("Hello BusConf\n")
if (r.status_code == 200):
    print("bus-conf.org is up running")
else:
    print("bus-conf.org is down")
